### ISSUE TITLE
Domino AMI not visible on AWS

### ISSUE THREAD

**Issue by learningpath1388** [HCL-TECH-SOFTWARE/domino-on-aws#1]
I tried to follow below documentation.
https://opensource.hcltechsw.com/domino-on-aws/deployment-steps/

However, I couldnot find Domino AMI.
Please guide on same.

**Comment by pavangit1990** [comment]
yes even i am not able to find Domino AMI

**Comment by thampel** [comment]
This documentation repository has been built in preparation of releasing the AMI to the marketplace.
To date, the AMI has not been published yet. When it is published, you will need to purchase the product first before you can see the AMI.
